apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-101
spec: 
  config: '{
  "cniVersion": "0.3.1",
  "name": "macvlan-conf-101",
  "type": "macvlan",
  "master": "enp10s0.101",
  "mode": "bridge",
  "ipam": {
    "type": "static"
    }
    }'
